name: Deploy Supabase

run-name: Supabase - ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # TODO
    # env:
    #   SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    #   SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    #   SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Disabled Notice
        run: echo "Supabase deploy action is currently disabled."

      # - uses: actions/checkout@v4

      # - uses: supabase/setup-cli@v1
      #   with:
      #     version: latest

      # - name: Link to Supabase project
      #   run: supabase link --project-ref $SUPABASE_PROJECT_ID

      # - name: Push database migrations
      #   run: supabase db push

      # - name: Deploy Edge Functions
      #   run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
